start-at-login = true
automatically-unhide-macos-hidden-apps = true
after-startup-command = [
  'exec-and-forget borders active_color=0xffefe3b5 inactive_color=0xff2e2e2e width=5 hidpi=on style=round'
]
on-focus-changed = 'move-mouse window-lazy-center'

[gaps]
    inner.horizontal = 4
    inner.vertical =   4
    outer.left =       4
    outer.bottom =     4
    outer.top =        4
    outer.right =      4

[mode.main.binding]
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-left = 'join-with left'
    alt-down = 'join-with down'
    alt-up = 'join-with up'
    alt-right = 'join-with right'

    alt-f = 'macos-native-fullscreen'
    alt-q = 'close --quit-if-last-window'

    alt-b = 'exec-and-forget MOZ_DISABLE_SAFE_MODE_KEY=1 open -n -a "Zen"'
    alt-e = 'exec-and-forget kitty yazi ~'
    alt-t = 'exec-and-forget kitty ~'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
    alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
    alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
    alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
    alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
    alt-shift-0 = ['move-node-to-workspace 10', 'workspace 10']
