# catppuccin mocha — dark

set -g @theme_bg        "#1e1e2e"
set -g @theme_red       "#f38ba8"
set -g @theme_green     "#a6e3a1"
set -g @theme_overlay_0 "#6c7086"
set -g @theme_maroon    "#eba0ac"
set -g @theme_blue      "#89b4fa"
set -g @theme_yellow    "#f9e2af"
set -g @theme_pink      "#f5c2e7"
set -g @theme_surface_0 "#313244"
set -g @theme_mauve     "#cba6f7"
set -g @theme_rosewater "#f5e0dc"
set -g @theme_peach     "#fab387"
